# Generated by Django 3.1.5 on 2021-01-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisCode',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('category_code', models.CharField(max_length=100, null=True)),
                ('diagnosis_code', models.CharField(max_length=100, null=True)),
                ('short_description', models.TextField(null=True)),
                ('full_description', models.TextField()),
                ('category_title', models.CharField(max_length=255, null=True)),
                ('code_type', models.CharField(default='icd-10', max_length=10)),
            ],
        ),
    ]
